version: "3"
services:
  init:
    image: node:18
    profiles: ["init"]
    volumes:
      - ../../aula-docusaurus/:/src
    working_dir: /src
    command: npm install
  deploy:
    image: node:18
    profiles: ["deploy"]
    volumes:
      - ../../aula-docusaurus/:/src
    working_dir: /src
    environment:
      - GIT_USER=$GIT_USER
      - GIT_PASS=$GIT_PASS
      - GIT_NAME=$GIT_NAME
      - GIT_MAIL=$GIT_MAIL
      - USE_SSH=$USE_SSH
      - CURRENT_BRANCH=$CURRENT_BRANCH
    command: bash -c "git config --global user.email $GIT_MAIL && git config --global user.name $GIT_NAME && yarn deploy"

